// Main API instance - import from the apiClient.ts file
export { api } from '../apiClient';
export type { ApiResponse } from '@/types';

// Feature-specific API modules
export { authApi } from './auth';
export { usersApi } from './users';
export { coursesApi, courseReviewsApi, courseBundlesApi, courseWaitlistApi } from './courses';
export { waitlistApi } from './waitlist';
export type { WaitlistEntry, WaitlistStatus } from './waitlist';
export { courseComparisonApi } from './courseComparison';
export type { CourseComparisonResponse, CourseComparisonItem, ComparisonSummary } from './courseComparison';
export { learningPathsApi } from './learningPaths';
export { notificationsApi } from './notifications';
export { postsApi, commentsApi, projectsApi } from './social';
export { savedContentApi, type SavedContent, type SavedContentType } from './savedContent';
export { achievementsApi, badgesApi, challengesApi, leaderboardApi } from './gamification';
export { searchApi } from './search';
export { messagesApi } from './messages';
export { collaborativeProjectsApi } from './collaborativeProjects';
export { notesApi } from './notes';
export { flashcardsApi } from './flashcards';
export { certificatesApi } from './certificates';
export { forumsApi } from './forums';
export { lessonsApi } from './lessons';
export { modulesApi } from './modules';
export { courseCompletionApi } from './courseCompletion';
export { assignmentsApi } from './assignments';
export { submissionsApi } from './submissions';
export { uploadApi } from './upload';
export { pomodoroApi } from './pomodoro';
export { recommendationsApi } from './recommendations';
export { codePlaygroundApi } from './codePlayground';
export { analyticsApi } from './analytics';
export { learningGoalsApi } from './learningGoals';
export { mentorshipApi } from './mentorship';
export { mentorApplicationsApi } from './mentorApplications';
export { liveSessionsApi } from './liveSessions';
export { helpSupportApi } from './helpSupport';
export type { FAQ, HelpArticle, SupportTicket, VideoTutorial, FAQCategory, HelpArticleCategory, TicketStatus, TicketCategory, TicketPriority } from './helpSupport';
export { dataPrivacyApi } from './dataPrivacy';
export type { DataExport, CookieConsent, PrivacySettings, ExportStatus, ExportFormat, ExportOptions, CookieConsentPreferences } from './dataPrivacy';
export { courseSuggestionsApi } from './courseSuggestions';
export type { CourseSuggestion, SuggestionStatus, CreateSuggestionData } from './courseSuggestions';
export { referralsApi } from './referrals';
export type { Referral, ReferralStats, ReferralStatus, ReferralCode, CreateCustomReferralData, UseReferralData, RewardType, ReferralReward } from './referrals';
export { accessibilityApi } from './accessibility';
export type { AccessibilityPreferences, UpdateAccessibilityPreferencesData, FontSize, ColorBlindMode } from './accessibility';
export type { VideoProgress, VideoUploadResponse, YouTubeVideoResponse, UpdateVideoSettingsData } from './videos';
export { announcementsApi } from './announcements';
export type { Announcement, AnnouncementsResponse, CreateAnnouncementData, UpdateAnnouncementData, AnnouncementType, AnnouncementPriority, AnnouncementStatus, TargetAudience, GetAnnouncementsParams } from './announcements';

// Also export everything from each module
export * from './auth';
export * from './users';
export * from './courses';
export * from './waitlist';
export * from './courseComparison';
export * from './learningPaths';
export * from './notifications';
export * from './social';
export * from './gamification';
export * from './search';
export * from './messages';
export * from './notes';
export * from './flashcards';
export * from './certificates';
export * from './forums';
export * from './lessons';
export * from './modules';
export * from './videos';
export * from './courseCompletion';
export * from './assignments';
export * from './submissions';
export * from './codePlayground';
export * from './analytics';
export * from './learningGoals';
export * from './mentorship';
export * from './mentorApplications';
export * from './liveSessions';
export * from './helpSupport';
export * from './dataPrivacy';
export * from './courseSuggestions';
export * from './referrals';
export * from './accessibility';
export * from './announcements';

